Document: libgatha
Title: Debian libgatha Manual
Author: <insert document author here>
Abstract: This manual describes what libgatha is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libgatha/libgatha.sgml.gz

Format: postscript
Files: /usr/share/doc/libgatha/libgatha.ps.gz

Format: text
Files: /usr/share/doc/libgatha/libgatha.text.gz

Format: HTML
Index: /usr/share/doc/libgatha/html/index.html
Files: /usr/share/doc/libgatha/html/*.html
